# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=140)),
                ('content', models.CharField(max_length=9999)),
                ('excerpt', models.CharField(blank=True, max_length=300)),
                ('thumbnail', models.ImageField(blank=True, upload_to='')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.Community')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
