# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_auto_20171013_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='description',
            field=models.TextField(max_length=9999),
        ),
    ]
