# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_auto_20171013_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='short_link',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='title',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
