# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 16:32
from __future__ import unicode_literals

import apps.users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20171012_1000'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.users.models.UserManager()),
            ],
        ),
    ]
