# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20171012_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='content',
            field=models.TextField(max_length=9999),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='excerpt',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
