# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20171013_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='title',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
