# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20171016_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='content',
            field=models.TextField(blank=True, max_length=9999),
        ),
    ]
